const distractions = [
  "youtube.com",
  "twitch.tv",
  "reddit.com",
  "instagram.com",
  "checkboxrace.com",
  "onesquareminesweeper.com",
  "puginarug.com",
  "hooooooooo.com",
  "potatoortomato.com",
  "mondrianandme.com",
  "longdogechallenge.com",
  "facebook.com",
  "hackertyper.com",
  "onefishstudio.net",
  "cat-bounce.com",
  "pointerpointer.com",
  "ffffidget.com",
  "trypap.com",
  "smashthewalls.com",
  "thezen.zone",
  "creativetechguy.com",
  "tiktok.com",
  "discord.com/app",
  "4chan.org",
  "digg.com",
  "quora.com",
  "news.google.com",
  "myspace.com",
  "hulu.com",
  "netflix.com",
  "tumblr.com",
  "twitter.com",
  "vimeo.com",
  "en.wikipedia.org/wiki/Special:Random",
  "agar.io",
  "diep.io",
  "imgur.com",
  "imdb.com",
  "deviantart.com",
  "theonion.com",
  "soundcloud.com",
  "rottentomatoes.com",
  "ebay.com",
  "craigslist.org",
  "amazon.com",
  "foxnews.com",
  "buzzfeed.com",
  "cnet.com",
  "bleacherreport.com",
  "espn.com",
  "foxsports.com",
  "cbssports.com",
  "mlb.com",
  "nfl.com",
  "nhl.com",
  "nba.com",
  "techcrunch.com",
  "mashable.com",
  "engadget.com",
  "medium.com",
  "techmeme.com",
  "news.ycombinator.com",
  "wattpad.com",
];

const productivity = [
  "khanacademy.org",
  "edu",
  "cnx.org",
  "github.com",
  "gov",
  "hackclub.com",
  "hackclub.dev",
  "wikipedia.org",
  "wikiversity.org",
  "wikibooks.org",
  "wiktionary.org",
  "gmail.com",
  "bbc.com",
  "forbes.com",
  "economist.com",
  "nbcnews.com",
  "cnn.com",
  "msnbc.com",
  "huffingtonpost.com",
  "businessinsider.com",
  "nytimes.com",
  "bloomberg.com",
  "usatoday.com",
  "washingtonpost.com",
  "theguardian.com",
  "npr.org",
  "wsj.com",
  "time.com",
  "cnbc.com",
  "tenor.com",
  "giphy.com",
  "crunchyroll.com",
  "w3schools.com",
  "stackoverflow.com",
  "openculture.com",
];

var productivityList = [];
for (var i = 0; i < productivity.length; i++) {
  productivityList[i] = "*://*." + productivity[i] + "/*";
}

chrome.webRequest.onBeforeRequest.addListener(
  function () {
    return {
      redirectUrl:
        "https://" +
        distractions[Math.floor(Math.random() * distractions.length)],
    };
  },
  {
    urls: productivityList,
    types: [
      "main_frame",
      "sub_frame",
      "stylesheet",
      "script",
      "image",
      "object",
      "xmlhttprequest",
      "other",
    ],
  },
  ["blocking"]
);
